greatSumini/pickk-admin

pages/login.tsx
src/components/organisms/GFooter.tsx
src/components/organisms/LoginFooter.tsx
src/components/organisms/LoginForm.tsx
src/components/templates/MainLayout.tsx

[구현] LoginPage UI 구현

---

src/components/molecules/BoardFilter/BodyRow.tsx
src/components/organisms/Board/Filter/Body.tsx
src/components/organisms/Board/Filter/ButtonArea.tsx
src/components/organisms/Board/Filter/Header.tsx
src/components/organisms/Board/Filter/index.tsx
src/components/templates/Board.tsx
src/contexts/BoardFilter.tsx

src/components/organisms/Board/Filter/index, Body 추가
src/context/BoardFilter 추가

[Feature] Add BoardFilter

---

src/components/molecules/button/CardReload.tsx
src/components/organisms/Dashboard/Card/Header.tsx
src/lib/DateParser.ts

[Feature] add dashboard-card-header

---

src/components/molecules/button/CardReload.tsx
src/components/organisms/Dashboard/Card/Body.tsx
src/components/organisms/Dashboard/Card/Header.tsx

[Feature] Add DashboardCardBody

---

pages/claim/cancel.tsx
pages/claim/exchange.tsx
pages/claim/return.tsx
pages/delivery/index.tsx
pages/order/index.tsx
pages/products/index.tsx
src/components/molecules/Row/Discount/Influencer.tsx
src/components/molecules/Row/Discount/Subscription.tsx
src/components/organisms/Board/Table/DiscountSection/Influencer.tsx
src/components/organisms/Board/Table/DiscountSection/index.tsx
src/components/organisms/Board/Table/index.tsx

[Feature] Add Table Discount Section

---

pages/products/index.tsx
src/components/atoms/img/index.tsx
src/components/molecules/Row/Discount/Influencer.tsx
src/components/organisms/Board/Table/DiscountSection/Influencer.tsx
src/components/organisms/Modal/Phase0.tsx
src/components/organisms/Modal/Phase1.tsx
src/components/organisms/Modal/index.tsx

[Feature] Add influnencer discount modal

---

src/components/organisms/GHeader.tsx
src/components/organisms/LoginForm.tsx
src/lib/services/User.ts

[Feature] Add User Service

---

src/lib/services/Item.ts
src/lib/services/Product.ts
src/types/Item.ts
src/types/Product.ts

[Feature] add stock,products service

---

src/board/placement/index.tsx
src/board/placement/preview/index.tsx
src/components/molecules/button/preview/index.tsx
src/contexts/Board.tsx

[Enhance] Refactor placement preview

---

src/board/item/index.tsx
src/board/item/inputs.ts
src/board/item/table/actions.ts
src/board/item/table/index.ts
src/components/molecules/BoardFilter/BodyRow.tsx
src/components/molecules/BoardFilter/input/InputBox.tsx
src/components/organisms/Board/Table/ActionBar.tsx
src/components/organisms/Board/Table/index.tsx
src/contexts/Board.tsx
src/lib/services/Item.ts

[Feature] add item action buttons

---

src/board/placement/index.tsx
src/contexts/Board.tsx
src/hooks/table/Item.ts
src/hooks/table/Placement.ts
src/lib/services/Item.ts
src/lib/services/Placement.ts
src/types/Order.ts
src/types/Placement.ts

[Feature] add placements service hooks types

---

package-lock.json
package.json
src/board/item/index.tsx
src/board/placement/index.tsx
src/board/placement/table/actions.tsx
src/board/placement/table/columns.tsx
src/board/placement/table/data-parser.ts
src/board/placement/table/index.ts
src/components/molecules/button/ExcelDownload.tsx
src/components/organisms/Board/Table/ActionBar.tsx
src/components/organisms/Board/Table/table.d.ts
src/contexts/Board.tsx

[Feature] add excel import logic

---

src/board/placement/table/columns.tsx
src/components/organisms/Board/Table/index.tsx

[Enhance] Apply scroll x to placement table

---

src/board/item/index.tsx
src/board/item/table/columns.tsx
src/board/item/table/stock-modal.tsx
src/components/organisms/Board/Table/ActionBar.tsx
src/hooks/table/Item.ts
src/lib/NumberParser.ts
src/lib/services/Product.ts

[Feature] Add stock manage modal

---

src/board/placement/index.tsx
src/board/placement/inputs.ts
src/board/placement/table/actions.tsx
src/board/placement/table/columns.tsx
src/components/molecules/BoardFilter/input/DatePicker.tsx
src/components/molecules/button/preview/index.tsx
src/contexts/Board.tsx
src/types/Placement.ts

[Enhance] change placement/inputs.ts

---

src/board/item/table/actions.ts
src/board/placement/index.tsx
src/board/placement/table/actions.tsx
src/components/organisms/Board/Table/ActionBar.tsx
src/components/organisms/Board/Table/table.d.ts
src/lib/services/Placement.ts

[Feature] add placement place action

---

src/board/placement/index.tsx
src/board/placement/table/actions.tsx
src/board/placement/table/modal/ship.tsx
src/components/organisms/Board/Table/index.tsx
src/contexts/Board.tsx
src/types/OrderItem.ts

[Feature] add placement ship action

---

src/board/placement/inputs.ts
src/components/molecules/picker/date-time.tsx
src/components/organisms/Board/Table/DiscountSection/subs-discount.tsx

[Enhance] add disabledDate,Time to picker/date-time

---

src/board/placement/index.tsx
src/board/placement/table/actions.tsx

[Enhance] add Placements:StockSetModal

---

src/board/settlements/amount-preview.tsx
src/board/settlements/index.tsx
src/board/settlements/preview-data.ts
src/components/organisms/Board/Filter/Header.tsx
src/hooks/Settlement.ts
src/lib/services/Settlement.ts
src/types/Settlement.ts

resolve #90, #97 
500 에러 해결까지 merge 보류

[Feature] add settlements preview

---

src/board/placement/index.tsx
src/types/Placement.ts

- 재고 설정시 보내기 위한 itemId
fix #98

[Bugfix] add Placements:itemId

---

package-lock.json
package.json
src/board/exchange-request/table/actions.ts
src/board/order-items/index.tsx
src/board/order-items/table/actions.ts
src/board/order-items/table/index.ts
src/lib/services/ExchangeRequest.ts
src/lib/services/OrderItem.ts

[Feature] add refund request switch actions

---

src/board/order-items/index.tsx
src/board/order-items/table/modal/exchangeRequest.tsx
src/board/refund-request/index.tsx
src/hooks/Item.ts
src/lib/services/Item.ts
src/lib/services/OrderItem.ts
src/lib/services/RefundRequest.ts
src/types/Item.ts

[Feature] add ExchangeRequest switch actions
